# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.4
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Focalworks addon for Hex Casting
display_name: Focalworks
github_repo: Focalworks
github_user: c-Caelum
java_package: io.github.c_caelum.focalworks
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mit_license: true
mod_version: 0.1.0
modid: focalworks
